### PR TITLE
Use graceful-fs

### PR DESCRIPTION
**Pull request by shinnn**
* I replaced built-in fs with [graceful-fs](https://github.com/isaacs/node-graceful-fs). graceful-fs is the safer version of fs. Actually, [gulp's file system](https://github.com/wearefractal/vinyl-fs) [uses it](https://github.com/wearefractal/vinyl-fs/blob/d0ba8bba4519df2b6bb41f0f07cfaf1d7a5fbf7d/lib/dest/writeContents/writeBuffer.js#L3).
* I removed mocha.opts file. Mocha uses `-R spec` and `-u bdd` options by default.
* I updated [should.js](https://github.com/shouldjs/should.js) to v5.0.

### CODE REVIEW

**Comment by jgable** [comment]
Published as 0.2.6 and added you as a publisher on NPM.

**Comment by shinnn** [comment]
Thanks. Could you add me as a collaborator of this repo, too?

**Comment by jgable** [comment]
Sorry, got this mixed up with the other project.  You're now a collaborator and owner on NPM of this project.  I haven't bumped and published, so feel free to whenever you want.

**Comment by shinnn** [comment]
Awesome!

**Comment by shinnn** [comment]
It seems that you made a typo. My username is `shinnn` (triple `n`), but you added `shinn` (double `n`).

image

**Comment by jgable** [comment]
Ha ha.  Good catch.  Should be all set now.

**Comment by shinnn** [comment]
Thanks :)

**Pull request merged**
